# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-hostisdown

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Check if the desired host is up or not
Version:    0.6.7
Release:    1
Group:      Qt/Qt
License:    MIT
URL:        https://scarpino.dev
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-hostisdown.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  desktop-file-utils

%description
An application to check if the desired host is up or not.

%if "%{?vendor}" == "chum"
PackageName: HostIsDown
Type: desktop-application
DeveloperName: Andrea Scarpino
Categories:
 - Network
 - Utility
Custom:
  Repo: https://github.com/ilpianista/harbour-HostIsDown
Icon: https://raw.githubusercontent.com/ilpianista/harbour-HostIsDown/master/icons/harbour-hostisdown.svg
Screenshots:
 - https://raw.githubusercontent.com/ilpianista/harbour-HostIsDown/master/screenshots/screenshot_1.png
 - https://raw.githubusercontent.com/ilpianista/harbour-HostIsDown/master/screenshots/screenshot_2.png
 - https://raw.githubusercontent.com/ilpianista/harbour-HostIsDown/master/screenshots/screenshot_3.png
Url:
  Homepage: https://github.com/ilpianista/harbour-HostIsDown
  Bugtracker: https://github.com/ilpianista/harbour-HostIsDown/issues
  Donation: https://liberapay.com/ilpianista
%endif


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%caps(cap_net_admin=ep cap_net_raw=ep) %{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
